### PR TITLE
Add Japanese support

### PR DESCRIPTION
**Pull request by TakayukiMatsuo**
**This PR has been recreated due to a change in repository visibility. Previous PR is #67**

This PR aims to add support for Japanese documentation to wolfSSH and wolfBoot.

Prerequisites:
Japanese font sets must be installed in the system. ”Noto Sans CJK JP” is required. The font files(7 files) could be downloaded from
(https://github.com/googlefonts/noto-cjk/tree/main/Sans/OTF/Japanese).

How to generate Japanese documents:
DOC_LANG variable is introduced to specify the target language. Pass DOC_LANG=JA option to make in each wolfBoot or wolfSSH directory. By default, English documents will be generated.

### CODE REVIEW

**Review by lealem47 — APPROVED** [review]

**Review by cconlon — APPROVED** [review]

**Comment by cconlon** [comment]
@kojo1 please review and re-assign back to me for final merge once ready. Thanks!

**Comment by TakayukiMatsuo** [comment]
Hi @kaleb-himes, The "Docs Build Test" for this PR seems to have failed due to lack of Japanese fonts in the test environment. Could you please install the missing fonts mentioned in the PR description?

**Comment by lealem47** [comment]
Hey @TakayukiMatsuo, the test should pass if you rebase on master after this commit https://github.com/wolfSSL/documentation/pull/73.  Also consider adding some documentation on how to install the Japanese fonts.

**Comment by TakayukiMatsuo** [comment]
Hi @lealem47 , along your suggestion, added a localization section to the 'README.md' of the documentation root. Font installation and the way to switch the document language are addressed there. 

Unfortunately, the test failed even after re-basing on master. Is anything missing in my side?

**Comment by dgarske** [comment]
@lealem47 is out of office for an extended break. The GitHub action still indicates "Noto Sans CJK JP" is missing. @TakayukiMatsuo you may need to investigate this on your own unless @cconlon can suggest another engineer to help.

**Comment by kaleb-himes** [comment]
@dgarske I am here to assist as needed, was working with Lealem on this last Friday. We have the fonts installed but they still are not being recognized.

**Comment by kaleb-himes** [comment]
https://github.com/wolfSSL/documentation/pull/74 should fix this issue, @lealem47 is going to rebase this PR shortly and hopefully we can have this merged before @TakayukiMatsuo comes online his Tuesday morning!

**Comment by lealem47** [comment]
Hey @TakayukiMatsuo, unfortunately I have not been able to get the test passing. Not sure why the GitHub actions environment can't find the fonts, but your instructions helped Kaleb and I get the Japanese manuals building on Jenkins so the code is all fine. Like David mentioned, I'll be out of office on an extended break so I won't be able continue getting the test to pass. The state of the PR is great and I think it's merge ready. I'll let @cconlon decide how to move forward.

**Pull request merged**
